const rows = [
  [
    'Amber Temple',
    'Pragmatic Play',
    'Video Slots',
    ['Egyptian', 'Adventure'],
    ['Free Spins', 'Multipliers'],
    25,
    8700,
    '2026-09-18',
    'amber',
    ['Featured', 'Top'],
  ],
  [
    'Wild Orchard',
    'Pragmatic Play',
    'Video Slots',
    ['Nature', 'Fruit'],
    ['Free Spins', 'Wilds'],
    20,
    7200,
    '2025-06-14',
    'green',
    ['Popular'],
  ],
  [
    'Moonlit Treasures',
    'Pragmatic Play',
    'Video Slots',
    ['Fantasy', 'Adventure'],
    ['Free Spins', 'Bonus Rounds'],
    30,
    6400,
    '2026-08-20',
    'purple',
    ['Featured'],
  ],
  [
    'Sands of Fortune',
    'NetEnt',
    'Video Slots',
    ['Egyptian', 'Adventure'],
    ['Free Spins', 'Wilds'],
    25,
    6900,
    '2025-11-03',
    'sand',
    ['Top'],
  ],
  [
    'Northern Lights',
    'NetEnt',
    'Video Slots',
    ['Nature', 'Fantasy'],
    ['Free Spins', 'Multipliers'],
    20,
    5300,
    '2026-09-27',
    'teal',
    ['Featured'],
  ],
  [
    'Clockwork City',
    'NetEnt',
    'Video Slots',
    ['Steampunk', 'Adventure'],
    ['Wilds', 'Bonus Rounds'],
    40,
    4800,
    '2024-10-12',
    'slate',
    [],
  ],
  [
    'Coral Kingdom',
    'Play’n GO',
    'Video Slots',
    ['Ocean', 'Adventure'],
    ['Free Spins', 'Wilds'],
    25,
    6100,
    '2026-06-12',
    'blue',
    ['Popular'],
  ],
  [
    'Jade Dynasty',
    'Play’n GO',
    'Video Slots',
    ['Asian', 'Fantasy'],
    ['Free Spins', 'Multipliers'],
    20,
    5600,
    '2025-03-17',
    'jade',
    [],
  ],
  [
    'Book of Horizons',
    'Play’n GO',
    'Video Slots',
    ['Egyptian', 'Adventure'],
    ['Free Spins', 'Expanding Wilds'],
    10,
    7800,
    '2024-04-22',
    'sand',
    ['Top'],
  ],
  [
    'Desert Bloom',
    'Red Tiger',
    'Video Slots',
    ['Egyptian', 'Nature'],
    ['Free Spins', 'Multipliers'],
    30,
    3400,
    '2026-09-30',
    'rose',
    ['Featured'],
  ],
  [
    'Neon Nights',
    'Red Tiger',
    'Video Slots',
    ['Music', 'Urban'],
    ['Wilds', 'Bonus Rounds'],
    50,
    5800,
    '2025-07-15',
    'purple',
    ['Popular'],
  ],
  [
    'Golden Grove',
    'Red Tiger',
    'Video Slots',
    ['Nature', 'Fantasy'],
    ['Free Spins', 'Wilds'],
    25,
    3100,
    '2026-08-01',
    'green',
    [],
  ],
  [
    'Starlight Express',
    'Yggdrasil',
    'Video Slots',
    ['Space', 'Adventure'],
    ['Free Spins', 'Multipliers'],
    30,
    4200,
    '2026-09-23',
    'blue',
    ['Featured'],
  ],
  [
    'Viking Voyage',
    'Yggdrasil',
    'Video Slots',
    ['Norse', 'Adventure'],
    ['Free Spins', 'Bonus Rounds'],
    20,
    4100,
    '2024-02-09',
    'slate',
    [],
  ],
  [
    'Cosmic Cascade',
    'Relax Gaming',
    'Video Slots',
    ['Space', 'Fantasy'],
    ['Cascades', 'Multipliers'],
    243,
    6500,
    '2026-09-11',
    'purple',
    ['Top'],
  ],
  [
    'Lucky Lanterns',
    'Relax Gaming',
    'Video Slots',
    ['Asian', 'Festival'],
    ['Free Spins', 'Wilds'],
    25,
    3700,
    '2025-01-07',
    'rose',
    [],
  ],
  [
    'Studio Roulette',
    'Evolution',
    'Live Roulette',
    ['Classic', 'Studio'],
    ['Live Dealer'],
    0,
    9600,
    '2024-04-01',
    'red',
    ['Live', 'Top'],
  ],
  [
    'Velvet Blackjack',
    'Evolution',
    'Live Blackjack',
    ['Classic', 'Studio'],
    ['Live Dealer', 'Side Bets'],
    0,
    9100,
    '2025-05-01',
    'green',
    ['Live', 'Popular'],
  ],
  [
    'Dragon Baccarat',
    'Evolution',
    'Live Baccarat',
    ['Asian', 'Studio'],
    ['Live Dealer', 'Side Bets'],
    0,
    6800,
    '2026-07-03',
    'red',
    ['Live'],
  ],
  [
    'French Roulette Live',
    'Ezugi',
    'Live Roulette',
    ['Classic', 'Luxury'],
    ['Live Dealer'],
    0,
    5700,
    '2025-02-12',
    'blue',
    ['Live'],
  ],
  [
    'Blackjack Salon',
    'Ezugi',
    'Live Blackjack',
    ['Classic', 'Luxury'],
    ['Live Dealer', 'Side Bets'],
    0,
    5100,
    '2026-09-20',
    'slate',
    ['Live', 'Featured'],
  ],
  [
    'Royal Baccarat Live',
    'Ezugi',
    'Live Baccarat',
    ['Classic', 'Luxury'],
    ['Live Dealer'],
    0,
    3500,
    '2025-10-02',
    'purple',
    ['Live'],
  ],
  [
    'Classic 21',
    'NetEnt',
    'Blackjack',
    ['Classic'],
    ['Side Bets'],
    0,
    2800,
    '2023-08-05',
    'green',
    [],
  ],
  [
    'European Roulette',
    'Play’n GO',
    'Roulette',
    ['Classic'],
    ['Table Game'],
    0,
    3200,
    '2023-12-06',
    'red',
    [],
  ],
  [
    'Punto Banco',
    'Pragmatic Play',
    'Baccarat',
    ['Classic'],
    ['Table Game'],
    0,
    2200,
    '2024-06-11',
    'teal',
    [],
  ],
  [
    'River Poker',
    'Relax Gaming',
    'Poker',
    ['Classic', 'Western'],
    ['Table Game', 'Bonus Rounds'],
    0,
    3300,
    '2025-06-07',
    'blue',
    [],
  ],
  [
    'Skyward',
    'Spribe',
    'Crash',
    ['Aviation', 'Adventure'],
    ['Multipliers', 'Cash Out'],
    0,
    10200,
    '2026-05-10',
    'slate',
    ['Top', 'Popular'],
  ],
  [
    'Orbit Run',
    'Spribe',
    'Crash',
    ['Space'],
    ['Multipliers', 'Cash Out'],
    0,
    5500,
    '2026-09-25',
    'purple',
    ['Featured'],
  ],
  [
    'Bingo Garden',
    'Play’n GO',
    'Bingo',
    ['Nature'],
    ['Bonus Rounds'],
    0,
    1900,
    '2025-04-08',
    'green',
    [],
  ],
  [
    'Pocket Puzzles',
    'Yggdrasil',
    'Casual/Other',
    ['Adventure'],
    ['Instant Play'],
    0,
    1300,
    '2026-09-29',
    'amber',
    [],
  ],
  [
    'Ancient Vault',
    'Red Tiger',
    'Video Slots',
    ['Egyptian'],
    ['Free Spins'],
    20,
    12000,
    '2024-04-20',
    'sand',
    ['Top'],
  ],
  [
    'Retro Reels',
    'NetEnt',
    'Video Slots',
    ['Fruit', 'Classic'],
    ['Wilds'],
    5,
    900,
    '2022-01-05',
    'rose',
    [],
  ],
]
export const games = rows.map((r, i) => ({
  id: `g${String(i + 1).padStart(2, '0')}`,
  game_id: `mock-${1001 + i}`,
  game_code: r[0].toLowerCase().replaceAll(' ', '-'),
  game_url: '',
  name: r[0],
  product: r[1],
  category: r[2],
  categories: [r[2]],
  themes: r[3],
  features: r[4],
  paylines: r[5],
  weekly_session_count: r[6],
  created_at: `${r[7]}T00:00:00.000Z`,
  color: r[8],
  sub_groups: r[9],
  platforms: i === 28 ? ['mobile'] : i === 31 ? ['desktop'] : ['desktop', 'mobile'],
  enabled: i !== 30,
  status: i === 30 || i === 31 ? 'disabled' : 'active',
  source: 'synthetic',
  isBonusPlay: r[4].includes('Bonus Rounds'),
  isFreebet: r[4].includes('Free Spins'),
  url_thumb: '',
  url_background: '',
}))
if (new Set(games.map((g) => g.id)).size !== games.length)
  throw new Error('Duplicate mock game IDs')
// The catalogue is immutable. User-created state is persisted separately.
games.forEach((g) => {
  const arrayFields = ['themes', 'features', 'platforms', 'sub_groups', 'categories']
  arrayFields.forEach((k) => Object.freeze(g[k]))
  Object.freeze(g)
})
Object.freeze(games)
export const gameById = (id) => games.find((g) => g.id === id)
